project:
  type: book
  output-dir: _site

execute:
  freeze: auto

book:
  title: "An introduction to Pynapple"
  author:
  - name: Wolf De Wulf
    url: wulfdewolf.github.io
    email: wolf.de.wulf@ed.ac.uk
    orcid: 0000-0003-4286-6868
    corresponding: true
    affiliations:
      - id: UoE
        name: University of Edinburgh
        department: Institute for Neuroscience and Cardiovascular Research
        group: Nolan lab
        city: Edinburgh
        country: United Kingdom
  date: "02/06/2026"
  chapters:
    - pynapple_fundamentals.qmd
    - slides.qmd

format:
  html:
    theme:
      - cosmo
      - brand
