project:
  type: book
  output-dir: _site
  resources:
    - slides.html
    - slides_files

execute:
  freeze: auto

book:
  title: An introduction to Pynapple
  author:
    - name: Wolf De Wulf
      url: https://wulfdewolf.github.io
      email: wolf.de.wulf@ed.ac.uk
      orcid: 0000-0002-0219-3120
      corresponding: true
      affiliations:
        - id: UoE
          name: University of Edinburgh
          department: Institute for Neuroscience and Cardiovascular Research
          group: Nolan lab
          city: Edinburgh
          country: United Kingdom
        - id: Flatiron
          name: Flatiron Institute
          department: Center for Computational Neuroscience
          group: NeuroRSE
          city: New York
          country: United States
  sidebar:
    align: left
    style: floating
    collapse-level: 2
    pinned: false
    tools:
      - icon: link
        url: "https://pynapple.org"
        text: Pynapple website
  repo-url: "https://github.com/pynapple-org/pynapple"
  site-url: "https://pynapple.org"
  open-graph: true
  date: "02/06/2026"
  chapters:
    - index.qmd
    - origins.qmd
    - goal.qmd
    - part: Pynapple fundamentals
      chapters:
        - snippets/ts.qmd
        - snippets/tsgroup.qmd
        - snippets/tsd.qmd
        - snippets/tsdframe.qmd
        - snippets/intervalset.qmd
    - part: Interactions
      chapters:
        - snippets/timesupport.qmd
        - snippets/restrict.qmd
        - snippets/value_from.qmd
    - part: Wrangling
      chapters:
        - snippets/numpy.qmd
        - snippets/slicing.qmd
    - part: Core functions
      chapters:
        - snippets/binning.qmd
        - snippets/averaging.qmd
        - snippets/thresholding.qmd
        - snippets/smoothing.qmd
    - part: Advanced functions
      chapters:
        - snippets/correlogram.qmd
        - snippets/signal.qmd
        - snippets/perievent.qmd
        - snippets/tuning_curves.qmd
    - part: Integration with other packages
      chapters:
        - snippets/pynaviz.qmd
        - snippets/nemos.qmd
        - snippets/spikeinterface.qmd
    - part: Data
      chapters:
        - snippets/loading.qmd
        - snippets/streaming.qmd
    - part: Your turn
      chapters:
        - your-turn.qmd

format:
  html:
    page-layout: full
    theme:
      - flatly
    grid:
      margin-width: 1000px
