project:
  type: book
  output-dir: _site
  render:
    - "**/*.qmd"

execute:
  freeze: auto

book:
  title: "An introduction to Pynapple"
  author:
    - name: Wolf De Wulf
      url: https://wulfdewolf.github.io
      email: wolf.de.wulf@ed.ac.uk
      orcid: 0000-0002-0219-3120
      corresponding: true
      affiliations:
        - id: UoE
          name: University of Edinburgh
          department: Institute for Neuroscience and Cardiovascular Research
          group: Nolan lab
          city: Edinburgh
          country: United Kingdom
  date: "02/06/2026"
  chapters:
    - index.qmd
    - _slides.qmd

format:
  html:
    theme:
      - cosmo
      - brand
